### ISSUE TITLE
dogpile.cache 0.9.1 introduced pep517 regression

### ISSUE THREAD

**Issue by ssbarnea** [sqlalchemy/dogpile.cache#178] opened 2020-04-30 13:42 UTC
dogpile.cache 0.9.1 introduced pep517 regression which prevented its installation on some setups:
```
Collecting dogpile.cache>=0.6.5
  Downloading http://mirror.gra1.ovh.openstack.org/pypifiles/packages/e6/65/fa4a947926034cb4af5f469c376a21728b7fd8de4668fed757c3586f0eef/dogpile.cache-0.9.1.tar.gz (329 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'

:stderr:   ERROR: Command errored out with exit status 1:
   command: /home/zuul/test-python/bin/python /home/zuul/test-python/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpx9zntfdw
       cwd: /tmp/pip-install-9ep3va87/dogpile.cache
  Complete output (10 lines):
  Traceback (most recent call last):
    File "/home/zuul/test-python/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 257, in <module>
      main()
    File "/home/zuul/test-python/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 240, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/home/zuul/test-python/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 85, in get_requires_for_build_wheel
      backend = _build_backend()
    File "/home/zuul/test-python/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 76, in _build_backend
      obj = getattr(obj, path_part)
  AttributeError: module 'setuptools.build_meta' has no attribute '__legacy__'
  ----------------------------------------
ERROR: Command errored out with exit status 1: /home/zuul/test-python/bin/python /home/zuul/test-python/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpx9zntfdw Check the logs for full command output.
WARNING: You are using pip version 20.0.2; however, version 20.1 is available.
```

Full report at https://zuul.opendev.org/t/openstack/build/0a2a5ca6414f4e56b9508322cf01c9f4

**Comment by zzzeek** [comment] 2020-04-30 14:16
hi there -

there's been extended discussion about the pep517 issue here: https://github.com/sqlalchemy/sqlalchemy/issues/5207 

short answer is that dogpile.cache has added pyproject.toml as well, which turns on pip's pep517 mode, which then has all kinds of issues that overall will have to be resolved on the pip side and/or the community at large.  however there is no documented incompatibility about including a pyproject.toml file alongside setup.py .

we can seek to remove pyproject.toml from the build but for now, however this is only a workaround.   it is likely that there is something in your build environment that's stale or incompatible with pep517, try using a fresh install environment.     If you run pip with --no-use-pep517 that would allow the install to proceed.

**Comment by ssbarnea** [comment] 2020-04-30 14:23
@zzzeek Thanks for the quick reply. Lets keep issue open until we find a better solution. Use of `pyproject.toml` should not break installation, for example I already use it in projects like https://github.com/ansible-community/molecule/blob/master/pyproject.toml or https://github.com/ansible/ansible-lint/blob/master/pyproject.toml and they are not failing to install, on the same setups as dogpile.cache.

I think we may need bit of tuning to make both worlds happy.

**Comment by zzzeek** [comment] 2020-04-30 14:27
on the SQLAlchemy side we simply removed pyproject.toml from the MANIFEST file so that it's not in the build.   SQLAlchemy however builds C extensions so has a much more complicated situation.   

for dogpile, there's nothing unusual in setup.py, it's about as vanilla as it gets.  What sort of "tunings" did you have in mind?

**Comment by CaselIT** [comment] 2020-04-30 14:39
I think that the problem may be an old version of setuptools.
Probably removing it like in alembic/sqlalchemy for now should be ok.

Another option is to use pep517 specifying in the `pyproject.toml`
```
[build-system]	
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
```
Likely also specifying a min version for setuptools.

**Comment by CaselIT** [comment] 2020-04-30 14:42
But I'm not sure if the bug on debian regarding the broken pep517 package would still happen with that configuration.

All things considered it's probably best to sit out until it's in general use, since each time it was enabled, we got multiple issues regarding it, so it's clearly not ready for prime time yet.

**Comment by ssbarnea** [comment] 2020-04-30 15:30
I am already testing patch that adds required missing bits to pyproject.toml from the #179 at https://review.opendev.org/#/c/724691/ -- we will know soon.

It is a very common mistake to forget to add `[build-system]` when adding this file and we do know that missing these produces lots of failures. The proposed values where taken from molecule, as the packaging installation is tested across a wide range of distros.

**Comment by CaselIT** [comment] 2020-04-30 15:39
the problem here is that I think that the sensible default does not install an updated version of setuptools. ops I guess

**Comment by zzzeek** [comment] 2020-04-30 15:40
e.g., just like last time, this REALLY looks like a bug in pip/ setuptools / etc.    they have documented a default, and it seems to break all over the place.   if their default is unworkable, they should change it, or fix setuptools, or whatever.

**Comment by zzzeek** [comment] 2020-04-30 15:41
but their default includes a minimum version of setuptools "setuptools>=40.8.0" - is that wrong ?  did they mean to update it?

**Comment by ssbarnea** [comment] 2020-04-30 15:55
@zzzeek I did not test this project with older setuptools, I only copy/pasted values that I needed on other projects (which where raised due to specific bugs).

So, shortly it may work file even with older versions of both pip and setuptools. Still, who has time to test all possible combinations? Considering that these are not runtime requirements, it should be safer to use more recent versions when building the wheel.

Just to be clear for everyone: these requirements will not alter your system pip/setuptools when you build or install the package.

**Comment by zzzeek** [comment] 2020-04-30 16:07
as mentioned on the PR safest approach as we did in SQLAlchemy seems to omit this file from the builds.      I just remain pretty frustrated that this ongoing issue is not considered to be a bug in pip.

**Comment by FedericoRessi** [comment] 2020-05-04 08:10
I created this workaround for OpenStack projects: https://review.opendev.org/725209

**Comment by zzzeek** [comment] 2020-05-04 12:52
the irony is dogpile.cache is actually CI tested in centos8 containers, so no intrinsic incompatibility there.    ill just release without the pyproject.toml in the dist.

**Comment by sqla-tester** [comment] 2020-05-04 14:33
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Omit pyproject.toml from installation** https://gerrit.sqlalchemy.org/c/sqlalchemy/dogpile.cache/+/1941

**Comment by FedericoRessi** [comment] 2020-05-04 18:26
I can confirm the problem is also happening when installing dogpile.cache on RHEL 8

**Closed** 2020-05-04 20:18 UTC
Labels: question

**Comment by zzzeek** [comment] 2020-05-05 04:53
0.9.2 is released which should not include this file
