### ISSUE TITLE
Caching async functions

### ISSUE THREAD

**Issue by akrantz01** [sqlalchemy/dogpile.cache#200] opened 2021-04-04 18:49 UTC
Does dogpile.cache support caching async functions? If not, will it be supported at some point?

**Comment by zzzeek** [comment] 2021-04-05 02:25
not right now, and the issue to track this is literally right preceding this one at #199.    The methodology is straightforward but i dont know anyone is planning to work on this anytime soon.

**Comment by zzzeek** [comment] 2021-04-05 02:25
dupe of #199

**Closed by zzzeek** 2021-04-05 02:25 UTC
Labels: duplicate, question
